/**
 * Visual Scores Report Generator
 *
 * Generates a markdown report with visual judge scores for all pages in a book.
 */

import { VisualJudgment } from './testing/visual-judge'

// ============================================================================
// Types
// ============================================================================

export interface PageScore {
  pageNumber: number
  pageType: string
  title?: string
  judgment?: VisualJudgment
  error?: string
}

export interface BookScoresReport {
  bookName: string
  generatedAt: string
  totalPages: number
  scoredPages: number
  averageScore: number
  passedPages: number
  failedPages: number
  pageScores: PageScore[]
}

// ============================================================================
// Report Generation
// ============================================================================

/**
 * Generate a markdown report from page scores
 */
export function generateScoresMarkdown(report: BookScoresReport): string {
  const lines: string[] = []

  // Header
  lines.push(`# Visual Quality Report: ${report.bookName}`)
  lines.push('')
  lines.push(`Generated: ${report.generatedAt}`)
  lines.push('')

  // Summary
  lines.push('## Summary')
  lines.push('')
  lines.push('| Metric | Value |')
  lines.push('|--------|-------|')
  lines.push(`| Total Pages | ${report.totalPages} |`)
  lines.push(`| Scored Pages | ${report.scoredPages} |`)
  lines.push(`| Average Score | ${report.averageScore.toFixed(1)} |`)
  lines.push(`| Passed (>= 70) | ${report.passedPages} |`)
  lines.push(`| Failed (< 70) | ${report.failedPages} |`)
  lines.push(`| Pass Rate | ${((report.passedPages / Math.max(report.scoredPages, 1)) * 100).toFixed(1)}% |`)
  lines.push('')

  // Score distribution
  lines.push('## Score Distribution')
  lines.push('')
  lines.push('```')
  lines.push(generateScoreHistogram(report.pageScores))
  lines.push('```')
  lines.push('')

  // Detailed Scores
  lines.push('## Page Scores')
  lines.push('')
  lines.push('| Page | Type | Title | Score | Status |')
  lines.push('|------|------|-------|-------|--------|')

  for (const page of report.pageScores) {
    const score = page.judgment?.overallScore ?? 'N/A'
    const status = page.error
      ? 'Error'
      : page.judgment
      ? page.judgment.pass
        ? 'Pass'
        : 'Fail'
      : 'Skipped'
    const statusEmoji = status === 'Pass' ? '' : status === 'Fail' ? '' : ''

    lines.push(
      `| ${page.pageNumber} | ${page.pageType} | ${page.title || '-'} | ${score} | ${statusEmoji} ${status} |`
    )
  }
  lines.push('')

  // Issues Summary
  const pagesWithIssues = report.pageScores.filter(
    p => p.judgment && !p.judgment.pass && p.judgment.suggestions.length > 0
  )

  if (pagesWithIssues.length > 0) {
    lines.push('## Issues & Suggestions')
    lines.push('')

    for (const page of pagesWithIssues) {
      if (!page.judgment) continue

      lines.push(`### Page ${page.pageNumber}: ${page.pageType}`)
      lines.push('')
      lines.push(`**Score:** ${page.judgment.overallScore}`)
      lines.push('')
      lines.push(`**Summary:** ${page.judgment.summary}`)
      lines.push('')

      // Criteria breakdown
      lines.push('**Criteria Scores:**')
      lines.push(`- Print Readability: ${page.judgment.criteria.printReadability.score}`)
      lines.push(`- Layout Balance: ${page.judgment.criteria.layoutBalance.score}`)
      lines.push(`- Brand Cohesion: ${page.judgment.criteria.brandCohesion.score}`)
      lines.push('')

      // Issues
      const allIssues = [
        ...page.judgment.criteria.printReadability.issues,
        ...page.judgment.criteria.layoutBalance.issues,
        ...page.judgment.criteria.brandCohesion.issues,
      ].filter(Boolean)

      if (allIssues.length > 0) {
        lines.push('**Issues:**')
        for (const issue of allIssues) {
          lines.push(`- ${issue}`)
        }
        lines.push('')
      }

      // Suggestions
      if (page.judgment.suggestions.length > 0) {
        lines.push('**Suggestions:**')
        for (const suggestion of page.judgment.suggestions) {
          lines.push(`- ${suggestion}`)
        }
        lines.push('')
      }
    }
  }

  // Footer
  lines.push('---')
  lines.push('')
  lines.push('*Report generated by Strava Book Visual Judge*')

  return lines.join('\n')
}

/**
 * Generate a simple ASCII histogram of scores
 */
function generateScoreHistogram(pageScores: PageScore[]): string {
  const buckets: Record<string, number> = {
    '0-19': 0,
    '20-39': 0,
    '40-59': 0,
    '60-79': 0,
    '80-100': 0,
  }

  for (const page of pageScores) {
    const score = page.judgment?.overallScore ?? -1
    if (score < 0) continue

    if (score < 20) buckets['0-19']++
    else if (score < 40) buckets['20-39']++
    else if (score < 60) buckets['40-59']++
    else if (score < 80) buckets['60-79']++
    else buckets['80-100']++
  }

  const maxCount = Math.max(...Object.values(buckets), 1)
  const barWidth = 30

  const lines: string[] = []
  for (const [range, count] of Object.entries(buckets)) {
    const barLength = Math.round((count / maxCount) * barWidth)
    const bar = '#'.repeat(barLength)
    lines.push(`${range.padStart(7)}: ${bar.padEnd(barWidth)} (${count})`)
  }

  return lines.join('\n')
}

/**
 * Create a BookScoresReport from an array of page scores
 */
export function createBookScoresReport(
  bookName: string,
  pageScores: PageScore[]
): BookScoresReport {
  const scoredPages = pageScores.filter(p => p.judgment && !p.error)
  const scores = scoredPages.map(p => p.judgment!.overallScore)
  const averageScore = scores.length > 0
    ? scores.reduce((sum, s) => sum + s, 0) / scores.length
    : 0

  const passedPages = scoredPages.filter(p => p.judgment!.pass).length
  const failedPages = scoredPages.length - passedPages

  return {
    bookName,
    generatedAt: new Date().toISOString(),
    totalPages: pageScores.length,
    scoredPages: scoredPages.length,
    averageScore,
    passedPages,
    failedPages,
    pageScores,
  }
}

/**
 * Create a minimal report for when visual judging is skipped
 */
export function createSkippedReport(bookName: string, pageCount: number): string {
  const lines: string[] = [
    `# Visual Quality Report: ${bookName}`,
    '',
    `Generated: ${new Date().toISOString()}`,
    '',
    '## Summary',
    '',
    'Visual quality scoring was skipped for this book.',
    '',
    `Total Pages: ${pageCount}`,
    '',
    '---',
    '',
    '*Report generated by Strava Book*',
  ]

  return lines.join('\n')
}
