import { Page, Text, View, Document, StyleSheet } from '@react-pdf/renderer'
import { StravaActivity } from '@/lib/strava'
import { RacePageLeft } from './RacePageLeft'
import { RacePageRight } from './RacePageRight'

// Register a nice font if possible, using standard Helvetica for now
const styles = StyleSheet.create({
    page: {
        flexDirection: 'column',
        backgroundColor: '#FFFFFF',
        padding: 40,
    },
    header: {
        marginBottom: 20,
        borderBottomWidth: 2,
        borderBottomColor: '#000000',
        paddingBottom: 10,
    },
    title: {
        fontSize: 24,
        fontWeight: 'bold',
        fontFamily: 'Helvetica-Bold',
        marginBottom: 5,
        textTransform: 'uppercase',
    },
    date: {
        fontSize: 12,
        color: '#666666',
        fontFamily: 'Helvetica',
    },
    mapPlaceholder: {
        height: 300,
        backgroundColor: '#F0F0F0',
        justifyContent: 'center',
        alignItems: 'center',
        marginBottom: 30,
        borderRadius: 4,
    },
    statsGrid: {
        flexDirection: 'row',
        justifyContent: 'space-between',
        marginBottom: 20,
    },
    statBox: {
        alignItems: 'center',
    },
    statValue: {
        fontSize: 18,
        fontFamily: 'Helvetica-Bold',
    },
    statLabel: {
        fontSize: 10,
        color: '#888888',
        textTransform: 'uppercase',
        marginTop: 2,
    },
    footer: {
        position: 'absolute',
        bottom: 30,
        left: 40,
        right: 40,
        textAlign: 'center',
        fontSize: 10,
        color: '#AAAAAA',
    },
})

interface RacePageProps {
    activity: StravaActivity
    highlightLabel?: string
}

export const RacePageContent = ({ activity, highlightLabel }: RacePageProps) => (
    <Page size="LETTER" style={styles.page}>
        <View style={styles.header}>
            {highlightLabel && (
                <Text style={{ fontSize: 10, color: 'orange', textTransform: 'uppercase', marginBottom: 4 }}>
                    {highlightLabel}
                </Text>
            )}
            <Text style={styles.title}>{activity.name}</Text>
            <Text style={styles.date}>{new Date(activity.start_date).toLocaleDateString(undefined, {
                weekday: 'long',
                year: 'numeric',
                month: 'long',
                day: 'numeric'
            })}</Text>
        </View>

        <View style={styles.mapPlaceholder}>
            <Text style={{ color: '#999' }}>[ Map Image Placeholder ]</Text>
            <Text style={{ fontSize: 10, color: '#AAA', marginTop: 10 }}>
                {activity.map.summary_polyline.substring(0, 30)}...
            </Text>
        </View>

        <View style={styles.statsGrid}>
            <View style={styles.statBox}>
                <Text style={styles.statValue}>{(activity.distance / 1000).toFixed(2)} km</Text>
                <Text style={styles.statLabel}>Distance</Text>
            </View>
            <View style={styles.statBox}>
                <Text style={styles.statValue}>{(activity.moving_time / 60).toFixed(0)} min</Text>
                <Text style={styles.statLabel}>Moving Time</Text>
            </View>
            <View style={styles.statBox}>
                <Text style={styles.statValue}>{activity.total_elevation_gain} m</Text>
                <Text style={styles.statLabel}>Elevation</Text>
            </View>
        </View>

        <View style={styles.footer}>
            <Text>Generated by Strava Book • {activity.type}</Text>
        </View>
    </Page>
)

export interface RacePageSpreadProps {
    activity: StravaActivity
    mapboxToken?: string
    highlightLabel?: string
}

export const RacePageSpread = ({ activity, mapboxToken, highlightLabel }: RacePageSpreadProps) => (
    <Document>
        <RacePageLeft activity={activity} highlightLabel={highlightLabel} />
        <RacePageRight activity={activity} mapboxToken={mapboxToken} />
    </Document>
)

export const RacePage = ({ activity, mapboxToken }: { activity: StravaActivity, mapboxToken?: string }) => (
    <RacePageSpread activity={activity} mapboxToken={mapboxToken} />
)
