import { Page, Text, View, Document, StyleSheet } from '@react-pdf/renderer'
import { StravaActivity } from '@/lib/strava'
import { Race_2pLeft } from './Race_2pLeft'
import { Race_2pRight } from './Race_2pRight'
import { StatsGrid } from '@/components/pdf/StatsGrid'
import { Header } from '@/components/pdf/Header'

// Register a nice font if possible, using standard Helvetica for now
const styles = StyleSheet.create({
    page: {
        flexDirection: 'column',
        backgroundColor: '#FFFFFF',
        padding: 40,
    },

    mapPlaceholder: {
        height: 300,
        backgroundColor: '#F0F0F0',
        justifyContent: 'center',
        alignItems: 'center',
        marginBottom: 30,
        borderRadius: 4,
    },

    footer: {
        position: 'absolute',
        bottom: 30,
        left: 40,
        right: 40,
        textAlign: 'center',
        fontSize: 10,
        color: '#AAAAAA',
    },
})

interface Race_2pProps {
    activity: StravaActivity
    highlightLabel?: string
}

export const Race_2pContent = ({ activity }: Race_2pProps) => (
    <Page size="LETTER" style={styles.page}>
        <Header activity={activity} showLocation={false} />

        <View style={styles.mapPlaceholder}>
            <Text style={{ color: '#999' }}>[ Map Image Placeholder ]</Text>
            <Text style={{ fontSize: 10, color: '#AAA', marginTop: 10 }}>
                {activity.map.summary_polyline.substring(0, 30)}...
            </Text>
        </View>

        <StatsGrid activity={activity} />

        <View style={styles.footer}>
            <Text>Generated by Strava Book • {activity.type}</Text>
        </View>
    </Page>
)

export interface Race_2pSpreadProps {
    activity: StravaActivity
    mapboxToken?: string
    highlightLabel?: string
}

// Pages-only version for use in BookDocument (returns fragment of pages)
export const Race_2pSpreadPages = ({ activity, mapboxToken, highlightLabel }: Race_2pSpreadProps) => (
    <>
        <Race_2pLeft activity={activity} highlightLabel={highlightLabel} />
        <Race_2pRight activity={activity} mapboxToken={mapboxToken} />
    </>
)

// Standalone version with Document wrapper (for testing)
export const Race_2pSpread = ({ activity, mapboxToken, highlightLabel }: Race_2pSpreadProps) => (
    <Document>
        <Race_2pSpreadPages activity={activity} mapboxToken={mapboxToken} highlightLabel={highlightLabel} />
    </Document>
)

export const Race_2p = ({ activity, mapboxToken }: { activity: StravaActivity, mapboxToken?: string }) => (
    <Race_2pSpread activity={activity} mapboxToken={mapboxToken} />
)
